M48
; DRILL file {KiCad 9.0.0} date 2025-03-14T11:53:46-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-14T11:53:46-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
%
G90
G05
T1
X2.34Y-2.3
X2.34Y-2.4
X2.34Y-3.04
X2.34Y-3.14
X2.34Y-3.24
X4.975Y-2.3
X4.975Y-2.4
X4.975Y-2.5
M30
