M48
; DRILL file {KiCad 7.0.9} date Sunday, December 31, 2023 at 08:51:40 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-31T20:51:40-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
%
G90
G05
T1
X2.085Y-6.3
X2.2Y-6.385
X2.315Y-6.305
X3.325Y-1.74
X3.385Y-1.87
X3.53Y-1.855
T0
M30
